# Generated by Django 5.0.7 on 2024-07-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0005_uservisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
