# Generated by Django 5.0.7 on 2024-07-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0007_sitevisitcounter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisitcounter',
            name='user',
        ),
    ]
