# Generated by Django 5.0.7 on 2024-07-28 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0008_remove_sitevisitcounter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitcounter',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uservisit',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
