# Generated by Django 5.0.7 on 2024-07-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0011_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
