# Generated by Django 5.0.7 on 2024-08-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0014_order_executor_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='works/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
