# Generated by Django 5.0.7 on 2024-08-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0015_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
